trigger:
  branches:
    include:
      - feature1

jobs:
  - job: myJob
    pool:
      vmImage: 'ubuntu-latest'

    steps:
      - task: Bash@3
        displayName: 'First Task'
        # Your first task configuration goes here
        continueOnError: true  # Continue to the next step even if this task fails
        name: myTask

  - job: rerunFailedTaskJob
    dependsOn: myJob
    condition: succeededOrFailed()  # Run this job regardless of the previous job (myJob) result

    steps:
      - ${{ if eq(dependencies.myJob.myTask.result, 'Succeeded') }}:
          script: echo 'Next Task'
          displayName: 'Next Task'
        ${{ else }}:
          script: echo 'Rerun the task here'
          displayName: 'Rerun Task'
